'''Configurations.
'''
import os

#GENERAL CONFIGURATIONS
DEVICE='gpu'
MODEL_SAVE_FOLDER='./artifacts/'
GRAPH_SAVE_FOLDER='./graphs/'

#DATASET CONFIGURATIONS
DATASET_FOLDER_PATH=os.getcwd()+'/../weather_classification_bdd100k/'
BATCH_SIZE=128
IMAGE_WIDTH=224
IMAGE_HEIGHT=224
IMAGE_CHANNEL=3
SHUFFLE=True
PATCH_SIZE=16
NUM_WORKERS=8
RANDOM_AFFINE_ROTATION_RANGE=(30,70)
RANDOM_AFFINE_TRANSLATE_RANGE=(0.1, 0.3)
RANDOM_AFFINE_SCALE_RANGE=(0.5, 0.75)
COLOR_JITTER_BRIGHTNESS=0.5
COLOR_JITTER_HUE=0.3


#MODEL CONFgGURATIONS
TRANSFORMER_NETWORK_DEPTH=10
NUM_CLASSES=6 #I'm not using the unknown folder class for the weather dataset.
PROJECTION_DIM_KEYS=512
PROJECTION_DIM_VALUES=512
NUM_HEADS=8
ATTN_DROPOUT_PROB=0.2
FEEDFORWARD_PROJECTION_DIM=2048
FEEDFORWARD_DROPOUT_PROB=0.2

#TRAINING CONFIGURATIONS
TRAIN_EPOCH=501
LEARNING_RATE=0.001
SCHEDULER_GAMMA=0.9
SCHEDULER_STEP_SIZE=10




